const express = require('express')
const bodyParser = require('body-parser')
const cors = require('cors')
const morgan = require('morgan')
const app = express()
const xmlRouter = require(__dirname + '/../Routes/xmlRouter.js')
const postsRouter = require(__dirname + '/../Routes/postsRouter.js')
app.use(morgan('combined'))
app.use(bodyParser.json())
app.use(cors())
app.use('/xml', xmlRouter)
app.use('/posts', postsRouter)
app.listen(process.env.PORT || 8081)
